apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myadmin-web
  template:
    metadata:
      labels:
        app: myadmin-web
    spec:
      containers:
        - name: web
          image: zlorg/myadmin_web:latest
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  if ! psql -h database  -U zlorg -c 'SELECT 1'; then
                    exit 1
                  fi
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: DJANGO_SERVER_PORT
              value: "2000"
            - name: POSTGRES_USER
              value: zlorg
            - name: POSTGRES_PASSWORD
              value: GalsenDev2023
            - name: POSTGRES_DB
              value: my-admin
            - name: POSTGRES_HOST
              value: database
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: web-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: web-deployment
  ports:
    - name: http
      port: 2000
      targetPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: myadmin-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myadmin-database
  serviceName: database
  template:
    metadata:
      labels:
        app: myadmin-database
    spec:
      initContainers:
        - name: init-database
          image: postgres:13
          command: ["bash", "-c", "rm -rf /var/lib/postgresql/data/*"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: database
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              value: GalsenDev2023
            - name: POSTGRES_USER
              value: zlorg
            - name: POSTGRES_DB
              value: my-admin
            - name: PGDATA
              value: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
